// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttbwvysatpwjhwslqwfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0Ynd2eXNhdHB3amh3c2xxd2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxOTUwNDIsImV4cCI6MjA4NTc3MTA0Mn0.8X2R_28fRSCnRPaBsnlplHAs0DZ1bPyvOkYyjByCAxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});